name: Deploy to VPS

on:
  push:
    branches:
      - main  # adjust to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Upload script to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASS }}" scp -o StrictHostKeyChecking=no ./setup.sh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/setup.sh
          sshpass -p "${{ secrets.VPS_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'chmod +x /root/setup.sh'

      - name: Uninstall previous installation (option 3)
        continue-on-error: true
        run: |
          sshpass -p "${{ secrets.VPS_PASS }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            'TERM=xterm bash /root/setup.sh <<< "3"'

      - name: Install minimal setup (option 2)
        run: |
          sshpass -p "${{ secrets.VPS_PASS }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            'TERM=xterm bash /root/setup.sh <<< "2"'
